
language: python
python:
   "3.6.3"
install:
  - "pip install -r requirements.txt"
  - "pip install coverage"
  - "pip install coveralls"
services:
  - postgresql
before_script:
  - psql -c 'create database fast_food_fast_testing;' -U postgres
  - export APP_VAR=testing
script:
  - nosetests --with-coverage --cover-package=app && coverage report
after_success: coveralls